### ISSUE TITLE
Add tag "beste-schule"

### ISSUE THREAD

**Issue by cweiske** [OsiPog/bester-durchschnitt-app#1]
Please add the tag "beste-schule" so that we can find the app in https://github.com/topics/beste-schule

Please also on https://github.com/OsiPog/bestes-abi

**Comment by OsiPog** [comment]
Hab ich gemacht danke für den Hinweis. Rein aus Interesse, warum ist dir das wichtig?

**Comment by cweiske** [comment]
Danke!

Ich hab bei DuckDuckGo mit `beste schule github` nach Projekten zu "beste schule" gesucht und bin direkt auf https://github.com/topics/beste-schule gelandet. Deine Projekte waren da nicht mit aufgelistet; die habe ich erst durch eine githubeigene Suche gefunden.
